[[main]]
    name = "GitHub"
    url = "https://github.com/joshuaseligman18"
    weight = 100
    [main.params]
        icon = "github"
        showName = false
        target = "_blank"
[[main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/joshuaseligman18"
    weight = 101
    [main.params]
        icon = "linkedin"
        showName = false
        target = "_blank"

[[main]]
    name = "About"
    pageRef = "about"
    weight = 1

[[main]]
    name = "Projects"
    pageRef = "projects"
    weight = 2

[[main]]
    name = "Blog"
    pageRef = "blog"
    weight = 3

[[main]]
    name = "Resume"
    pageRef = "resume"
    weight = 4


[[footer]]
    name = "GitHub"
    url = "https://github.com/joshuaseligman18"
    weight = 100
    [footer.params]
        icon = "github"
        showName = false
        target = "_blank"
[[footer]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/joshuaseligman18"
    weight = 101
    [footer.params]
        icon = "linkedin"
        showName = false
        target = "_blank"

[[footer]]
    name = "About"
    pageRef = "about"
    weight = 1

[[footer]]
    name = "Projects"
    pageRef = "projects"
    weight = 2

[[footer]]
    name = "Blog"
    pageRef = "blog"
    weight = 3

[[footer]]
    name = "Resume"
    pageRef = "resume"
    weight = 4
