colorscheme = 'ocean'
defaultAppearanch = 'dark'
mainSections = ["blog"]
dateFormat = "January 2, 2006"

[article]
showAuthor = false

[list]
groupByYear = false

[homepage]
layout = 'profile'
showRecent = true

[author]
name = 'Josh Seligman'
image = 'img/author.jpg'
headline = 'Software Engineer'
links = [
    { 'github' = 'https://github.com/joshuaseligman18' },
    { 'linkedin' = 'https://www.linkedin.com/in/joshuaseligman18' },
    { 'email' = 'mailto:joshuaseligman18@gmail.com' }
]
